# Generated by Django 2.1.5 on 2019-02-06 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='translateorigin',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='translation.Project'),
        ),
    ]
