# Generated by Django 2.1.5 on 2019-02-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_auto_20190206_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translateorigin',
            name='project_name',
        ),
        migrations.AddField(
            model_name='partiallytranslated',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='translation.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatedtext',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='translation.Project'),
            preserve_default=False,
        ),
    ]
