# Generated by Django 2.1.5 on 2019-02-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_project'),
        ('translation', '0006_auto_20190207_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='translatedtext',
            name='project_name',
        ),
        migrations.AddField(
            model_name='translateorigin',
            name='project_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='profiles.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partiallytranslated',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='translation.LanguageText'),
        ),
        migrations.AlterField(
            model_name='translatedtext',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='translation.LanguageText'),
        ),
        migrations.AlterField(
            model_name='translateorigin',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='translation.LanguageText'),
        ),
    ]
