# Generated by Django 2.1.5 on 2019-02-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0008_auto_20190218_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedtext',
            name='origin_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='translation.TranslateOrigin'),
        ),
    ]
