# Generated by Django 2.1.5 on 2019-03-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0009_auto_20190224_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='translateorigin',
            name='can_be_tagged',
            field=models.BooleanField(default=False),
        ),
    ]
