# Generated by Django 2.1.5 on 2019-03-23 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0011_translateorigin_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedtext',
            name='tagged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.Profile'),
        ),
    ]
