# Generated by Django 2.1.5 on 2019-02-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.ManyToManyField(to='profiles.LanguageText'),
        ),
    ]
