# Generated by Django 2.1.5 on 2019-02-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190218_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contributions',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.ManyToManyField(blank=True, to='profiles.LanguageText'),
        ),
    ]
