# Generated by Django 2.1.5 on 2019-02-23 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190223_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dialect',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_tongue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother_tongue', to='profiles.LanguageText'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='all_the_languages', to='profiles.LanguageText'),
        ),
    ]
